//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orange.Common.Profile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orange.Common.Profile.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _COOKIE_USER_INFO_SECOND.
        /// </summary>
        internal static string _COOKIE_USER_INFO_SECOND {
            get {
                return ResourceManager.GetString("_COOKIE_USER_INFO_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar.
        /// </summary>
        internal static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __CheckoutCities__Cache__Key__.
        /// </summary>
        internal static string CitiesCacheKey {
            get {
                return ResourceManager.GetString("CitiesCacheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CitiesListUrl.
        /// </summary>
        internal static string CitiesListUrl {
            get {
                return ResourceManager.GetString("CitiesListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string CityID {
            get {
                return ResourceManager.GetString("CityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityListUrl.
        /// </summary>
        internal static string CityListUrl {
            get {
                return ResourceManager.GetString("CityListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityTargetWeb.
        /// </summary>
        internal static string CityTargetWeb {
            get {
                return ResourceManager.GetString("CityTargetWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string CommerceConstantNA {
            get {
                return ResourceManager.GetString("CommerceConstantNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralInfo.DialNumber.
        /// </summary>
        internal static string CommerceDialNumber {
            get {
                return ResourceManager.GetString("CommerceDialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralInfo.email_address.
        /// </summary>
        internal static string CommerceEmailAddress {
            get {
                return ResourceManager.GetString("CommerceEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralInfo.user_id.
        /// </summary>
        internal static string CommerceUserID {
            get {
                return ResourceManager.GetString("CommerceUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CookieExpirationInMinutes.
        /// </summary>
        internal static string CookieExpirationInMinutes {
            get {
                return ResourceManager.GetString("CookieExpirationInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar.
        /// </summary>
        internal static string CurrentLanguageArabic {
            get {
                return ResourceManager.GetString("CurrentLanguageArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string CurrentLanguageEnglish {
            get {
                return ResourceManager.GetString("CurrentLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education ID.
        /// </summary>
        internal static string EducationID {
            get {
                return ResourceManager.GetString("EducationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationListUrl.
        /// </summary>
        internal static string EducationListUrl {
            get {
                return ResourceManager.GetString("EducationListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationTargetWeb.
        /// </summary>
        internal static string EducationTargetWeb {
            get {
                return ResourceManager.GetString("EducationTargetWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \english.
        /// </summary>
        internal static string EnglishSite {
            get {
                return ResourceManager.GetString("EnglishSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en.
        /// </summary>
        internal static string EnglishSiteName {
            get {
                return ResourceManager.GetString("EnglishSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string IDTypeID {
            get {
                return ResourceManager.GetString("IDTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDTypeListUrl.
        /// </summary>
        internal static string IDTypeListUrl {
            get {
                return ResourceManager.GetString("IDTypeListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDTypeTargetWeb.
        /// </summary>
        internal static string IDTypeTargetWeb {
            get {
                return ResourceManager.GetString("IDTypeTargetWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordLength.
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession ID.
        /// </summary>
        internal static string ProfessionID {
            get {
                return ResourceManager.GetString("ProfessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfessionListUrl.
        /// </summary>
        internal static string ProfessionListUrl {
            get {
                return ResourceManager.GetString("ProfessionListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfessionTargetWeb.
        /// </summary>
        internal static string ProfessionTargetWeb {
            get {
                return ResourceManager.GetString("ProfessionTargetWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;OrderBy&amp;gt;
        ///      &amp;lt;FieldRef Name=&quot;{0}&quot; /&amp;gt;
        ///   &amp;lt;/OrderBy&amp;gt;.
        /// </summary>
        internal static string Query_GetAllCities {
            get {
                return ResourceManager.GetString("Query_GetAllCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rmdn.
        /// </summary>
        internal static string RememberMeCookieName {
            get {
                return ResourceManager.GetString("RememberMeCookieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Title.
        /// </summary>
        internal static string SPTitleArabic {
            get {
                return ResourceManager.GetString("SPTitleArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArabicTitle.
        /// </summary>
        internal static string SPTitleArabicWithNoSpace {
            get {
                return ResourceManager.GetString("SPTitleArabicWithNoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string SPTitleEnglish {
            get {
                return ResourceManager.GetString("SPTitleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ThreeString {
            get {
                return ResourceManager.GetString("ThreeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TwoString {
            get {
                return ResourceManager.GetString("TwoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string userTicketSplitter {
            get {
                return ResourceManager.GetString("userTicketSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
